version: "3.9"

services:
  db:
    container_name: mongerdb
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=monger
      - MYSQL_ROOT_PASSWORD=MonGer812
